//Constants for getting all blogs

export const ALL_COCKTAILS_REQUEST="ALL_COCKTAILS_REQUEST";
export const ALL_COCKTAILS_SUCCESS="ALL_COCKTAILS_SUCCESS";
export const ALL_COCKTAILS_FAIL="ALL_COCKTAILS_FAIL";


export const ONLY_COCKTAILS_REQUEST="ONLY_COCKTAILS_REQUEST";
export const ONLY_COCKTAILS_SUCCESS="ONLY_COCKTAILS_SUCCESS";
export const ONLY_COCKTAILS_FAIL="ONLY_COCKTAILS_FAIL";