const PartyInfo=[
    {
        title:"Service Center",
        category:"developmet",
        party:"SAP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"People appreciate governemnt for new center",
        category:"accomplishment",
        img:"SAP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:9,
        reference:"partiopedia"    },
    {
        title:"Service Center",
        category:"accomplishment",
        img:"SAP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:18,      
        reference:"partiopedia"
    },
    {
        title:"School for village students",
        category:"useful",
        img:"SAP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:6,
        reference:"partiopedia"    },
    {
        title:"Market for village people",
        category:"useful",
        img:"SAP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:9,
        reference:"partiopedia"    },
    {
        title:"Village roads repaired",
        category:"developmet",
        party:"SAP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:2,
        reference:"partiopedia"    },
    {
        title:"Service Center",
        category:"developmet",
        party:"GGP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"People appreciate governemnt for new center",
        category:"accomplishment",
        img:"GGP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:9,
        reference:"partiopedia"    },
    {
        title:"Service Center",
        category:"accomplishment",
        img:"GGP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"School for village students",
        category:"useful",
        img:"GGP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"Market for village people",
        category:"useful",
        img:"GGP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"Village roads repaired",
        category:"developmet",
        party:"GGP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"School for village students",
        category:"useful",
        img:"LLP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"Market for village people",
        category:"useful",
        img:"LLP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"Village roads repaired",
        category:"developmet",
        party:"LLP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"Service Center",
        category:"developmet",
        party:"LLP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"People appreciate governemnt for new center",
        category:"accomplishment",
        img:"GGP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:9,
        reference:"partiopedia"    },
    {
        title:"Service Center",
        category:"accomplishment",
        img:"LLP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
    {
        title:"School for village students",
        category:"useful",
        img:"LLP",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
   {
        title:"Village roads repaired",
        category:"developmet",
        party:"LLP",
        img:"",
        content:"A recent project we worked on is a great example of how to align these three strands. In this instance, we were brought in to develop a new employee application that would combine multiple existing services in one place. The organisation had attempted this in the past with limited success, so when we became involved we decided to take the whole process back one step and ask why we were doing it.         Looking beyond the application, we asked employees to feedback their experiences in the broadest possible way and incorporated feedback from other stakeholders. Anonymity encouraged honesty and we were able to define a clear purpose for the organisation around respect for the individuals that made it up",
        usefulcount:8,
        reference:"partiopedia"    },
];

export default PartyInfo;